### ISSUE TITLE
[Feature Request]: Opt out TS transpilation

### ISSUE THREAD

**Issue by geromegrignon** [realworld-angular/realworld-angular-starter#3]
### Description

Introduced with 18.1, you can opt-out TS transpilation with ESBuild by updating the `tsconfg.json` file.

### Describe the solution you'd like

Update the `tsconfig.json`file based on this info: https://x.com/Jean__Meche/status/1820160258997657857

**Comment by ZvSimon** [comment]
Hi Greg ! 
I would like to take care of this issue. 

Best regards,

Simon

**Comment by geromegrignon** [comment]
Thanks @ZvSimon, I assigned you the task

**Comment by geromegrignon** [comment]
Completed
